### ISSUE TITLE
[TODO] Report新規作成

### ISSUE THREAD

**Issue by tkming0916** [YoslabEngineers/seminar-report-editor#15]
# 概要

レポートの新規作成

# 目的

レポートを新規作成してDBに格納するため

# 提案内容

# タスク

- [x] 作成するエンドポイント（User情報・Report情報受け取り）createReport
- [x] アプリケーション層:レポート作成用ドメインサービスの呼び出し
- [x] インフラ層のDBに入れるサービスの呼び出し
- [x] DB入れる（ReportContentは格納しない）

**Comment by sueCalystegia00** [comment]
クライアント(ユーザ)側から見ると処理は プレゼンテーション層(エンドポイント)→アプリケーション層→ドメイン層→インフラ層 の順に進むけど、
開発はその逆順に進めるのが基本的な流れだと思うので、まずはDBにデータを入れる処理から実装していくと良いと思う

初めての実装だと思うのでちょっと詳しく説明を書いていきます。
分かりづらい部分があれば遠慮なく質問してください。

## インフラ層
DBとの疎通部分。今回はドメイン層から受け取ったオブジェクトをDBのテーブルに書き込む処理。

### ORM
DBとの接続が必要になるので、ORM(Object-Relational Mapping)が別途必要。
> phpでは同様のものとして PDO などを触ったことがあるかもしれない

今回はTypescriptを使うためメジャーなORMとして Prisma を提案しておきます。
> https://www.prisma.io/nextjs

- [x] `next-app/src/lib/prisma` のディレクトリを作成
- [x] DB接続のための設定値を管理するファイルを作成(phpで connect_db みたいな設定ファイルを作ったことがあるかと)

DBへの接続値(hostやname, password)などはもちろん環境変数で管理すること。

### リポジトリ
メイン処理部分。ドメイン層とDBの橋渡し。ORMを呼び出して疎通を担当する。

- [x] `next-app/src/app/_repository/report.ts` を作成
- [x] `insertReport()` を実装
    - [x] ドメインオブジェクトを引数にとる
    - [x] DB書き込みを行う
    - [x] 書き込みの成功/失敗を返す

## ドメイン層
レポートのドメインオブジェクトを必要に応じて加工し、リポジトリに渡す処理。
今回はレポートの新規作成となるため、レポートに必要な要素(タイトルや提出日、etc...)を受け取って、レポートのドメインオブジェクトを作成し、問題なければリポジトリに登録を依頼するといった流れ。

- [x] `next-app/src/app/_domain/service/reportService.ts` を作成
- [x] `createReport()` を実装
    - 引数はレポートのドメインオブジェクトを作成するのに必要最低限なオブジェクト
    - レポートとして破綻するデータがあれば弾くバリデーションを実装(←考える。なければスキップ)
    - レポートのドメインオブジェクトのオブジェクトを生成して返す
- [x] `saveReport()` を実装
    - レポートのドメインオブジェクトを引数に受け取る
    - リポジトリに渡す
    - 保存の成功/失敗を返す

## アプリケーション層
エンドポイントに送られたリクエストデータを簡易なバリデーションで確認し、必要なドメインサービスを呼び出す。

- [x] `next-app/src/app/_application/service/registerReport.ts` を作成
- [x] `registerNewReport()` を実装
    -  引数にエンドポイントへ渡ってきたリクエストデータを受け取る
    - ドメインサービスを呼び出し、リクエストデータを基にレポートのドメインオブジェクトを取得する
    - ドメインサービスを呼び出し、取得したドメインオブジェクトの保存を依頼する
    - 成功/失敗を返す

## プレゼンテーション層(エンドポイント)
APIとしての窓口。リクエストを受け取る。

- [x] `next-app/src/app/api/v1/report/route.ts` を作成(Next.jsでは `api/` 配下の `route.ts` のパスがエンドポイントとなる)
- [x] reportRequestHandler() を実装
    - HTTPメソッドが `POST` である判定
    - リクエストボディに必要なデータが揃っているか確認
    - 過不足なければアプリケーション層を呼び出し、レポートの新規作成を依頼
    - 保存の成功/失敗をステータス・レスポンスとして返す


ファイル名や関数名はかなりテキトーです。「より適切な命名がないか」はよく考えてみてください。
またざっと書き出しただけなので、実装が不十分な箇所があるかもしれません。適宜追加・修正してください。

**Comment by tagahei** [comment]
prisma実行 よく使うからメモ

DBの内容を持ってくる
```
npx prisma db pull --schema=./src/lib/prisma/schema.prisma
```

Prismaの型生成？
```
npx prisma generate --schema=./src/lib/prisma/schema.prisma
```

**Comment by sueCalystegia00** [comment]
@banamon prismaのディレクトリにREADME配置して書いとけば？

**Comment by tagahei** [comment]
## レスポンスを返そうっつ！

参考になりそうなもの
- https://nextjs.org/docs/app/building-your-application/routing/route-handlers#request-body
- nextResponse: https://nextjs.org/docs/app/api-reference/functions/next-response#json

**Comment by tagahei** [comment]
テスとカキカキします
- https://zenn.dev/takumi_n/scraps/18b18819f92ce2
パターン２の同じディレクトリ下にtestディレクトリを入れてやります
