### ISSUE TITLE
[TODO] テキストスタイルボタンの適用

### ISSUE THREAD

**Issue by sueCalystegia00** [YoslabEngineers/seminar-report-editor#29]
# 概要

太字や斜体のアイコンを押したときに入力に反映されるようにする

# 目的

マークダウン記法に慣れていないひとのためにUIを実装する

# 提案内容

- components/Editor のアップデート
- (必要であれば) アイコンをコンポーネントに切り出し

# タスク

- [ ] テキスト選択 → ＃(見出し) をクリック → 選択したテキストの前に `#` を挿入
- [ ] テキスト選択 → B(太字) をクリック → 選択したテキストの前後に `**` を挿入
- [ ] テキスト選択 → I(斜体) をクリック → 選択したテキストの前後に `__` を挿入
- [ ] テキスト選択 → U(下線) をクリック → 選択したテキストの前後に ？？ を挿入(採用するマークダウンパターンに対応するもの)
- [ ] テキスト選択 → S(取り消し線) をクリック → 選択したテキストの前後に ？？ を挿入(採用するマークダウンパターンに対応するもの)
